=== locbinhthuong/C-ng-ngh-XML/buoi_03_nguyentanloc/order.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="orders">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="order" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="customer" type="xs:string"/>
							<xs:element name="products">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="product" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="name" type="xs:string"/>
												</xs:sequence>
												<xs:attribute name="id" type="xs:string" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:unique name="UniqueProductIdWithinOrder">
										<xs:selector xpath="product"/>
										<xs:field xpath="@id"/>
									</xs:unique>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:ID" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:unique name="UniqueOrderIdDocWide">
				<xs:selector xpath="order"/>
				<xs:field xpath="@id"/>
			</xs:unique>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== locbinhthuong/C-ng-ngh-XML/buoi_03_nguyentanloc/order.xml
<orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="order.xsd">
	<order id="O001">
		<customer>SV01</customer>
		<products>
			<product id="P01">
				<name>Bút bi</name>
			</product>
			<product id="P02">
				<name>Tập giấy</name>
			</product>
		</products>
	</order>
	<order id="O002">
		<customer>SV02</customer>
		<products>
			<product id="P01">
				<name>Thước kẻ</name>
			</product>
		</products>
	</order>
</orders>
